// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF-DEn39JuWtwxYIyJYMiOeo82R4InLVg',
    appId: '1:673256708614:web:333fd324587e62d4e60187',
    messagingSenderId: '673256708614',
    projectId: 'paint-inventory-management',
    authDomain: 'paint-inventory-management.firebaseapp.com',
    storageBucket: 'paint-inventory-management.firebasestorage.app',
    measurementId: 'G-Y7LNEJ0Q3R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtnJF5cvzL0mtY83HQTYWGJTWalcrmTOU',
    appId: '1:673256708614:android:655b53b4679267e8e60187',
    messagingSenderId: '673256708614',
    projectId: 'paint-inventory-management',
    storageBucket: 'paint-inventory-management.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5R8uo0oTiXCUvCMxpBXQDeU024sgTeDA',
    appId: '1:673256708614:ios:fe532c733f238b54e60187',
    messagingSenderId: '673256708614',
    projectId: 'paint-inventory-management',
    storageBucket: 'paint-inventory-management.firebasestorage.app',
    iosBundleId: 'com.example.paintInventoryManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDF-DEn39JuWtwxYIyJYMiOeo82R4InLVg',
    appId: '1:673256708614:web:93caeba081c0f78de60187',
    messagingSenderId: '673256708614',
    projectId: 'paint-inventory-management',
    authDomain: 'paint-inventory-management.firebaseapp.com',
    storageBucket: 'paint-inventory-management.firebasestorage.app',
    measurementId: 'G-N64TWZ1L7L',
  );
}
